parameters:
    env: 'DEV'
    url: 'http://lovesimplefw.app/'
    db_config:
        driver   : 'mysql'
        host     : 'localhost'
        database  : 'larproject1'
        username  : 'homestead'
        password  : 'secret'
        charset   : 'utf8'
        collation : 'utf8_unicode_ci'
        prefix    : ''