default:
    page: "home@welcome"
GET:
    "cate/index/":
        page: "CateController@index"
    "cate/{id}/edit":
        page: "CateController@edit"
    "cate/create/":
        page: "CateController@create"
    "cate/{id}/delete":
        page: "CateController@delete"
POST:
    "cate/store/":
        page: "CateController@store"
PUT:
    "cate/{id}":
        page: "CateController@update"
