parameters:
    template_dir: "../templates"
    data_dir: "../data"
services:
    loader:
        class: Twig_Loader_Filesystem
        arguments: ['%template_dir%']
    twig:
        class: Twig_Environment
        arguments: ['@loader']
    adapter:
        class: League\Flysystem\Adapter\Local
        arguments: ['%data_dir%']
    filesystem:
        class: League\Flysystem\Filesystem
        arguments: ['@adapter']
    config_service:
        class: LoveSimple\Service\ConfigService
        arguments: ['@filesystem']
    contact_controller:
        class: LoveSimple\Controller\ContactController
        arguments: ['@twig']
    basic_page_controller:
        class: LoveSimple\Controller\BasicAppController
        arguments: ['@twig','@config_service']